CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE
    PASSWORD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ideas (
    ID INTEGER PRIMARY KEY NOT NULL,
    CREATED_BY TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    IMPACT INTEGER NOT NULL,
    EASE INTEGER NOT NULL,
    CONFIDENCE INTEGER NOT NULL,
    CREATION_TIME INTEGER NOT NULL
);
